import type { Metadata } from "next";
import { Anton, Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

import "@smastrom/react-rating/style.css";
import "./globals.css";
import "react-big-calendar/lib/css/react-big-calendar.css";
import { TanstackProvider } from "@/providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const anton = Anton({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Ker Active Users",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable}  ${anton.variable}`}>
        <NextTopLoader color='#008080' showSpinner={false} />
        <TanstackProvider>{children}</TanstackProvider>
        <Toaster />
      </body>
    </html>
  );
}
